[tool.poetry]
name = "bla"
version = "21.8.2"
description = "Common utilities and tools maintained by Greenbone Networks"
authors = ["Greenbone Networks GmbH <info@greenbone.net>"]
license = "GPL-3.0-or-later"
readme = "README.md"

classifiers=[
  # Full list: https://pypi.org/pypi?%3Aaction=list_classifiers
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",  # pylint: disable=line-too-long
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.5",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

packages = [
  { include = "test_workflow"},
  { include = "poetry.lock", format = "sdist" },
  { include = "poetry.toml", format = "sdist" },
]

[tool.poetry.dependencies]
python = "^3.7"
colorful = "^0.5.4"
tomlkit = ">=0.5.11"
packaging = "^20.3"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]
pylint = "^2.9.6"
autohooks = "^21.7.0"
autohooks-plugin-pylint = "^21.6.0"
autohooks-plugin-black = {version = "^21.7.1", python = "^3.6"}
black = {version = "21.7b0", python = "^3.6"}
rope = "^0.19.0"
coverage = "^5.5"

[tool.black]
line-length = 80
target-version = ['py35', 'py36', 'py37', 'py38']
skip-string-normalization = true
exclude = '''
/(
    \.git
  | \.hg
  | \.venv
  | \.circleci
  | \.github
  | \.vscode
  | _build
  | build
  | dist
  | docs
)/
'''

[tool.autohooks]
pre-commit = ['autohooks.plugins.black', 'autohooks.plugins.pylint']
mode = "poetry"

[tool.pontos.version]
version-module-file = "test_workflow/__version__.py"

[tool.poetry.scripts]
pontos-version = 'pontos.version:main'
pontos-release = 'pontos.release:main'
pontos-update-header = 'pontos.updateheader:main'
pontos-changelog = 'pontos.changelog:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

