name: Test GPG

on:
  push:
    branches: [ master ]

jobs:
  rebase:
    name: Rebase Dependabot
    runs-on: 'ubuntu-latest'
    steps:
      - name: Use AGENT
        run: gpg -h
      - name: Bla
        run: echo "Build and push ${{ github.repository }}-$GITHUB_BASE_REF-${{ matrix.platform}}-${{matrix.compiler}}-${{matrix.purpose}}"