name: Test GPG

on:
  push:
    branches: [ master ]

jobs:
  rebase:
    name: Rebase Dependabot
    runs-on: 'ubuntu-latest'
    steps:
      - name: Use AGENT
        run: gpg -h
      - name: Find reference branch
        run: |
          if [ -n "$GITHUB_BASE_REF" ];                          \
          then echo "BRANCH=$GITHUB_BASE_REF" >> $GITHUB_ENV;  \
          else echo "BRANCH=$GITHUB_REF" >> $GITHUB_ENV;       \
          fi
      - name: print branch
        run: echo $BRANCH