name: Test Rusty-Rust thingies

on:
  push:
    branches: [ master ]

jobs:
  test-create-changelog:
    env:
      GPG_KEY: ${{ secrets.GPG_KEY }}
      GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    name: Test Create Changelog
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
      # with:
      #   fetch-depth: 0
    #this doesn't work ...
    # - uses: actions/cache@v2
    #   with:
    #     path: |
    #       ~/.cargo/bin/
    #       ~/.cargo/registry/index/
    #       ~/.cargo/registry/cache/
    #       ~/.cargo/git/db/
    #       ~/.cargo/.crates.toml
    #       ~/.cargo/.crates2.json
    #       target/
    #     key: ${{ runner.os }}-cargo
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
    # - run: cargo -V
    #- name: git log
    #  run: git log
    - name: git fetch
      run: |
        git fetch --prune --unshallow --tags
        git tag
    - name: install git-cliff
      run: cargo install git-cliff
    - name: "Create CHANGELOG.md file"
      run: git-cliff -v -u
    - name: get latest tag
      run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV;
    - name: increment tag (patch)
      run: echo ${{env.TAG}} | awk -F. -v OFS=. '{++$NF; print;}'
