name: Test Rusty-Rust thingies

on:
  push:
    branches: [ master ]

jobs:
  test-create-changelog:
    env:
      GPG_KEY: ${{ secrets.GPG_KEY }}
      GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    name: Test Create Changelog
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: git-cliff
    - name: "Create CHANGELOG.md file"
      run: git-cliff -v -u