name: Release Python package with pontos

on:
  push:
    branches: 
      - master

jobs:
  test-gpg-sign:
    env:
      GPG_KEY: ${{ secrets.GPG_KEY }}
      GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    name: Test GPG
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Sign assets with pontos
      run: |
        #mkdir ~/.gnupg
        #echo -e "use-agent\npinentry-mode loopback" >> ~/.gnupg/gpg.conf
        #echo -e "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
        #echo RELOADAGENT | gpg-connect-agent
        echo -e "${{ env.GPG_KEY }}" >> tmp.file
        gpg --pinentry-mode loopback --import tmp.file && rm tmp.file
        gpg --list-secret-keys
